using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Selectorjuegos : MonoBehaviour {

    public GameObject J1;
    public GameObject J2;
    public GameObject J3;
    public GameObject J4;
    public GameObject J5;
    public GameObject J6;
    public GameObject J7;
    public GameObject J8;
    public GameObject J9;
    public GameObject J10;
    public GameObject J11;
    public GameObject J12;
    public GameObject J13;
    public GameObject J14;
    public GameObject J15;
    public GameObject J16;
    public GameObject J17;
    public GameObject J18;
    public GameObject J19;
    public GameObject J20;
    public GameObject J21;
    public GameObject J22;
    public GameObject J23;
    public GameObject J24;
    public GameObject J25;
    public GameObject J26;
    public GameObject J27;
    public GameObject J28;
    public GameObject J29;
    public GameObject J30;
    public GameObject J31;
    public GameObject J32;
    public GameObject J33;
    public GameObject J34;
    public GameObject J35;

    void Start () {
		
	}
	
	// Update is called once per frame
	void Update () {
        if (Controlador.Juegoselec == 0)
        {
            J1.SetActive(false);
            J2.SetActive(false);
            J3.SetActive(false);
            J4.SetActive(false);
            J5.SetActive(false);
            J6.SetActive(false);
            J7.SetActive(false);
            J8.SetActive(false);
            J9.SetActive(false);
            J10.SetActive(false);
            J11.SetActive(false);
            J12.SetActive(false);
            J13.SetActive(false);
            J14.SetActive(false);
            J15.SetActive(false);
            J16.SetActive(false);
            J17.SetActive(false);
            J18.SetActive(false);
            J19.SetActive(false);
            J20.SetActive(false);
            J21.SetActive(false);
            J22.SetActive(false);
            J23.SetActive(false);
            J24.SetActive(false);
            J25.SetActive(false);
            J26.SetActive(false);
            J27.SetActive(false);
            J28.SetActive(false);
            J29.SetActive(false);
            J30.SetActive(false);
            J31.SetActive(false);
            J32.SetActive(false);
            J33.SetActive(false);
            J34.SetActive(false);
            J35.SetActive(false);
        }
        if (Controlador.Juegoselec == 1)
        {
            J1.SetActive (true);
            J2.SetActive (false);
            J3.SetActive(false);
            J4.SetActive(false);
            J5.SetActive(false);
            J6.SetActive(false);
            J7.SetActive(false);
            J8.SetActive(false);
            J9.SetActive(false);
            J10.SetActive(false);
            J11.SetActive(false);
            J12.SetActive(false);
            J13.SetActive(false);
            J14.SetActive(false);
            J15.SetActive(false);
            J16.SetActive(false);
            J17.SetActive(false);
            J18.SetActive(false);
            J19.SetActive(false);
            J20.SetActive(false);
            J21.SetActive(false);
            J22.SetActive(false);
            J23.SetActive(false);
            J24.SetActive(false);
            J25.SetActive(false);
            J26.SetActive(false);
            J27.SetActive(false);
            J28.SetActive(false);
            J29.SetActive(false);
            J30.SetActive(false);
            J31.SetActive(false);
            J32.SetActive(false);
            J33.SetActive(false);
            J34.SetActive(false);
            J35.SetActive(false);
        }
        if (Controlador.Juegoselec == 2)
        {
            J1.SetActive(false);
            J2.SetActive(true);
            J3.SetActive(false);
            J4.SetActive(false);
            J5.SetActive(false);
            J6.SetActive(false);
            J7.SetActive(false);
            J8.SetActive(false);
            J9.SetActive(false);
            J10.SetActive(false);
            J11.SetActive(false);
            J12.SetActive(false);
            J13.SetActive(false);
            J14.SetActive(false);
            J15.SetActive(false);
            J16.SetActive(false);
            J17.SetActive(false);
            J18.SetActive(false);
            J19.SetActive(false);
            J20.SetActive(false);
            J21.SetActive(false);
            J22.SetActive(false);
            J23.SetActive(false);
            J24.SetActive(false);
            J25.SetActive(false);
            J26.SetActive(false);
            J27.SetActive(false);
            J28.SetActive(false);
            J29.SetActive(false);
            J30.SetActive(false);
            J31.SetActive(false);
            J32.SetActive(false);
            J33.SetActive(false);
            J34.SetActive(false);
            J35.SetActive(false);
        }
        if (Controlador.Juegoselec == 3)
        {
            J1.SetActive(false);
            J2.SetActive(false);
            J3.SetActive(true);
            J4.SetActive(false);
            J5.SetActive(false);
            J6.SetActive(false);
            J7.SetActive(false);
            J8.SetActive(false);
            J9.SetActive(false);
            J10.SetActive(false);
            J11.SetActive(false);
            J12.SetActive(false);
            J13.SetActive(false);
            J14.SetActive(false);
            J15.SetActive(false);
            J16.SetActive(false);
            J17.SetActive(false);
            J18.SetActive(false);
            J19.SetActive(false);
            J20.SetActive(false);
            J21.SetActive(false);
            J22.SetActive(false);
            J23.SetActive(false);
            J24.SetActive(false);
            J25.SetActive(false);
            J26.SetActive(false);
            J27.SetActive(false);
            J28.SetActive(false);
            J29.SetActive(false);
            J30.SetActive(false);
            J31.SetActive(false);
            J32.SetActive(false);
            J33.SetActive(false);
            J34.SetActive(false);
            J35.SetActive(false);
        }
        if (Controlador.Juegoselec == 4)
        {
            J1.SetActive(false);
            J2.SetActive(false);
            J3.SetActive(false);
            J4.SetActive(true);
            J5.SetActive(false);
            J6.SetActive(false);
            J7.SetActive(false);
            J8.SetActive(false);
            J9.SetActive(false);
            J10.SetActive(false);
            J11.SetActive(false);
            J12.SetActive(false);
            J13.SetActive(false);
            J14.SetActive(false);
            J15.SetActive(false);
            J16.SetActive(false);
            J17.SetActive(false);
            J18.SetActive(false);
            J19.SetActive(false);
            J20.SetActive(false);
            J21.SetActive(false);
            J22.SetActive(false);
            J23.SetActive(false);
            J24.SetActive(false);
            J25.SetActive(false);
            J26.SetActive(false);
            J27.SetActive(false);
            J28.SetActive(false);
            J29.SetActive(false);
            J30.SetActive(false);
            J31.SetActive(false);
            J32.SetActive(false);
            J33.SetActive(false);
            J34.SetActive(false);
            J35.SetActive(false);
        }
        if (Controlador.Juegoselec == 5)
        {
            J1.SetActive(false);
            J2.SetActive(false);
            J3.SetActive(false);
            J4.SetActive(false);
            J5.SetActive(true);
            J6.SetActive(false);
            J7.SetActive(false);
            J8.SetActive(false);
            J9.SetActive(false);
            J10.SetActive(false);
            J11.SetActive(false);
            J12.SetActive(false);
            J13.SetActive(false);
            J14.SetActive(false);
            J15.SetActive(false);
            J16.SetActive(false);
            J17.SetActive(false);
            J18.SetActive(false);
            J19.SetActive(false);
            J20.SetActive(false);
            J21.SetActive(false);
            J22.SetActive(false);
            J23.SetActive(false);
            J24.SetActive(false);
            J25.SetActive(false);
            J26.SetActive(false);
            J27.SetActive(false);
            J28.SetActive(false);
            J29.SetActive(false);
            J30.SetActive(false);
            J31.SetActive(false);
            J32.SetActive(false);
            J33.SetActive(false);
            J34.SetActive(false);
            J35.SetActive(false);
        }
        if (Controlador.Juegoselec == 6)
        {
            J1.SetActive(false);
            J2.SetActive(false);
            J3.SetActive(false);
            J4.SetActive(false);
            J5.SetActive(false);
            J6.SetActive(true);
            J7.SetActive(false);
            J8.SetActive(false);
            J9.SetActive(false);
            J10.SetActive(false);
            J11.SetActive(false);
            J12.SetActive(false);
            J13.SetActive(false);
            J14.SetActive(false);
            J15.SetActive(false);
            J16.SetActive(false);
            J17.SetActive(false);
            J18.SetActive(false);
            J19.SetActive(false);
            J20.SetActive(false);
            J21.SetActive(false);
            J22.SetActive(false);
            J23.SetActive(false);
            J24.SetActive(false);
            J25.SetActive(false);
            J26.SetActive(false);
            J27.SetActive(false);
            J28.SetActive(false);
            J29.SetActive(false);
            J30.SetActive(false);
            J31.SetActive(false);
            J32.SetActive(false);
            J33.SetActive(false);
            J34.SetActive(false);
            J35.SetActive(false);
        }
        if (Controlador.Juegoselec == 7)
        {
            J1.SetActive(false);
            J2.SetActive(false);
            J3.SetActive(false);
            J4.SetActive(false);
            J5.SetActive(false);
            J6.SetActive(false);
            J7.SetActive(true);
            J8.SetActive(false);
            J9.SetActive(false);
            J10.SetActive(false);
            J11.SetActive(false);
            J12.SetActive(false);
            J13.SetActive(false);
            J14.SetActive(false);
            J15.SetActive(false);
            J16.SetActive(false);
            J17.SetActive(false);
            J18.SetActive(false);
            J19.SetActive(false);
            J20.SetActive(false);
            J21.SetActive(false);
            J22.SetActive(false);
            J23.SetActive(false);
            J24.SetActive(false);
            J25.SetActive(false);
            J26.SetActive(false);
            J27.SetActive(false);
            J28.SetActive(false);
            J29.SetActive(false);
            J30.SetActive(false);
            J31.SetActive(false);
            J32.SetActive(false);
            J33.SetActive(false);
            J34.SetActive(false);
            J35.SetActive(false);
        }
        if (Controlador.Juegoselec == 8)
        {
            J1.SetActive(false);
            J2.SetActive(false);
            J3.SetActive(false);
            J4.SetActive(false);
            J5.SetActive(false);
            J6.SetActive(false);
            J7.SetActive(false);
            J8.SetActive(true);
            J9.SetActive(false);
            J10.SetActive(false);
            J11.SetActive(false);
            J12.SetActive(false);
            J13.SetActive(false);
            J14.SetActive(false);
            J15.SetActive(false);
            J16.SetActive(false);
            J17.SetActive(false);
            J18.SetActive(false);
            J19.SetActive(false);
            J20.SetActive(false);
            J21.SetActive(false);
            J22.SetActive(false);
            J23.SetActive(false);
            J24.SetActive(false);
            J25.SetActive(false);
            J26.SetActive(false);
            J27.SetActive(false);
            J28.SetActive(false);
            J29.SetActive(false);
            J30.SetActive(false);
            J31.SetActive(false);
            J32.SetActive(false);
            J33.SetActive(false);
            J34.SetActive(false);
            J35.SetActive(false);
        }
        if (Controlador.Juegoselec == 9)
        {
            J1.SetActive(false);
            J2.SetActive(false);
            J3.SetActive(false);
            J4.SetActive(false);
            J5.SetActive(false);
            J6.SetActive(false);
            J7.SetActive(false);
            J8.SetActive(false);
            J9.SetActive(true);
            J10.SetActive(false);
            J11.SetActive(false);
            J12.SetActive(false);
            J13.SetActive(false);
            J14.SetActive(false);
            J15.SetActive(false);
            J16.SetActive(false);
            J17.SetActive(false);
            J18.SetActive(false);
            J19.SetActive(false);
            J20.SetActive(false);
            J21.SetActive(false);
            J22.SetActive(false);
            J23.SetActive(false);
            J24.SetActive(false);
            J25.SetActive(false);
            J26.SetActive(false);
            J27.SetActive(false);
            J28.SetActive(false);
            J29.SetActive(false);
            J30.SetActive(false);
            J31.SetActive(false);
            J32.SetActive(false);
            J33.SetActive(false);
            J34.SetActive(false);
            J35.SetActive(false);
        }
        if (Controlador.Juegoselec == 10)
        {
            J1.SetActive(false);
            J2.SetActive(false);
            J3.SetActive(false);
            J4.SetActive(false);
            J5.SetActive(false);
            J6.SetActive(false);
            J7.SetActive(false);
            J8.SetActive(false);
            J9.SetActive(false);
            J10.SetActive(true);
            J11.SetActive(false);
            J12.SetActive(false);
            J13.SetActive(false);
            J14.SetActive(false);
            J15.SetActive(false);
            J16.SetActive(false);
            J17.SetActive(false);
            J18.SetActive(false);
            J19.SetActive(false);
            J20.SetActive(false);
            J21.SetActive(false);
            J22.SetActive(false);
            J23.SetActive(false);
            J24.SetActive(false);
            J25.SetActive(false);
            J26.SetActive(false);
            J27.SetActive(false);
            J28.SetActive(false);
            J29.SetActive(false);
            J30.SetActive(false);
            J31.SetActive(false);
            J32.SetActive(false);
            J33.SetActive(false);
            J34.SetActive(false);
            J35.SetActive(false);
        }
        if (Controlador.Juegoselec == 11)
        {
            J1.SetActive(false);
            J2.SetActive(false);
            J3.SetActive(false);
            J4.SetActive(false);
            J5.SetActive(false);
            J6.SetActive(false);
            J7.SetActive(false);
            J8.SetActive(false);
            J9.SetActive(false);
            J10.SetActive(false);
            J11.SetActive(true);
            J12.SetActive(false);
            J13.SetActive(false);
            J14.SetActive(false);
            J15.SetActive(false);
            J16.SetActive(false);
            J17.SetActive(false);
            J18.SetActive(false);
            J19.SetActive(false);
            J20.SetActive(false);
            J21.SetActive(false);
            J22.SetActive(false);
            J23.SetActive(false);
            J24.SetActive(false);
            J25.SetActive(false);
            J26.SetActive(false);
            J27.SetActive(false);
            J28.SetActive(false);
            J29.SetActive(false);
            J30.SetActive(false);
            J31.SetActive(false);
            J32.SetActive(false);
            J33.SetActive(false);
            J34.SetActive(false);
            J35.SetActive(false);
        }

        if (Controlador.Juegoselec == 12)
        {
            J1.SetActive(false);
            J2.SetActive(false);
            J3.SetActive(false);
            J4.SetActive(false);
            J5.SetActive(false);
            J6.SetActive(false);
            J7.SetActive(false);
            J8.SetActive(false);
            J9.SetActive(false);
            J10.SetActive(false);
            J11.SetActive(false);
            J12.SetActive(true);
            J13.SetActive(false);
            J14.SetActive(false);
            J15.SetActive(false);
            J16.SetActive(false);
            J17.SetActive(false);
            J18.SetActive(false);
            J19.SetActive(false);
            J20.SetActive(false);
            J21.SetActive(false);
            J22.SetActive(false);
            J23.SetActive(false);
            J24.SetActive(false);
            J25.SetActive(false);
            J26.SetActive(false);
            J27.SetActive(false);
            J28.SetActive(false);
            J29.SetActive(false);
            J30.SetActive(false);
            J31.SetActive(false);
            J32.SetActive(false);
            J33.SetActive(false);
            J34.SetActive(false);
            J35.SetActive(false);
        }

        if (Controlador.Juegoselec == 13)
        {
            J1.SetActive(false);
            J2.SetActive(false);
            J3.SetActive(false);
            J4.SetActive(false);
            J5.SetActive(false);
            J6.SetActive(false);
            J7.SetActive(false);
            J8.SetActive(false);
            J9.SetActive(false);
            J10.SetActive(false);
            J11.SetActive(false);
            J12.SetActive(false);
            J13.SetActive(true);
            J14.SetActive(false);
            J15.SetActive(false);
            J16.SetActive(false);
            J17.SetActive(false);
            J18.SetActive(false);
            J19.SetActive(false);
            J20.SetActive(false);
            J21.SetActive(false);
            J22.SetActive(false);
            J23.SetActive(false);
            J24.SetActive(false);
            J25.SetActive(false);
            J26.SetActive(false);
            J27.SetActive(false);
            J28.SetActive(false);
            J29.SetActive(false);
            J30.SetActive(false);
            J31.SetActive(false);
            J32.SetActive(false);
            J33.SetActive(false);
            J34.SetActive(false);
            J35.SetActive(false);
        }

        if (Controlador.Juegoselec == 14)
        {
            J1.SetActive(false);
            J2.SetActive(false);
            J3.SetActive(false);
            J4.SetActive(false);
            J5.SetActive(false);
            J6.SetActive(false);
            J7.SetActive(false);
            J8.SetActive(false);
            J9.SetActive(false);
            J10.SetActive(false);
            J11.SetActive(false);
            J12.SetActive(false);
            J13.SetActive(false);
            J14.SetActive(true);
            J15.SetActive(false);
            J16.SetActive(false);
            J17.SetActive(false);
            J18.SetActive(false);
            J19.SetActive(false);
            J20.SetActive(false);
            J21.SetActive(false);
            J22.SetActive(false);
            J23.SetActive(false);
            J24.SetActive(false);
            J25.SetActive(false);
            J26.SetActive(false);
            J27.SetActive(false);
            J28.SetActive(false);
            J29.SetActive(false);
            J30.SetActive(false);
            J31.SetActive(false);
            J32.SetActive(false);
            J33.SetActive(false);
            J34.SetActive(false);
            J35.SetActive(false);
        }

        if (Controlador.Juegoselec == 15)
        {
            J1.SetActive(false);
            J2.SetActive(false);
            J3.SetActive(false);
            J4.SetActive(false);
            J5.SetActive(false);
            J6.SetActive(false);
            J7.SetActive(false);
            J8.SetActive(false);
            J9.SetActive(false);
            J10.SetActive(false);
            J11.SetActive(false);
            J12.SetActive(false);
            J13.SetActive(false);
            J14.SetActive(false);
            J15.SetActive(true);
            J16.SetActive(false);
            J17.SetActive(false);
            J18.SetActive(false);
            J19.SetActive(false);
            J20.SetActive(false);
            J21.SetActive(false);
            J22.SetActive(false);
            J23.SetActive(false);
            J24.SetActive(false);
            J25.SetActive(false);
            J26.SetActive(false);
            J27.SetActive(false);
            J28.SetActive(false);
            J29.SetActive(false);
            J30.SetActive(false);
            J31.SetActive(false);
            J32.SetActive(false);
            J33.SetActive(false);
            J34.SetActive(false);
            J35.SetActive(false);
        }

        if (Controlador.Juegoselec == 16)
        {
            J1.SetActive(false);
            J2.SetActive(false);
            J3.SetActive(false);
            J4.SetActive(false);
            J5.SetActive(false);
            J6.SetActive(false);
            J7.SetActive(false);
            J8.SetActive(false);
            J9.SetActive(false);
            J10.SetActive(false);
            J11.SetActive(false);
            J12.SetActive(false);
            J13.SetActive(false);
            J14.SetActive(false);
            J15.SetActive(false);
            J16.SetActive(true);
            J17.SetActive(false);
            J18.SetActive(false);
            J19.SetActive(false);
            J20.SetActive(false);
            J21.SetActive(false);
            J22.SetActive(false);
            J23.SetActive(false);
            J24.SetActive(false);
            J25.SetActive(false);
            J26.SetActive(false);
            J27.SetActive(false);
            J28.SetActive(false);
            J29.SetActive(false);
            J30.SetActive(false);
            J31.SetActive(false);
            J32.SetActive(false);
            J33.SetActive(false);
            J34.SetActive(false);
            J35.SetActive(false);
        }

        if (Controlador.Juegoselec == 17)
        {
            J1.SetActive(false);
            J2.SetActive(false);
            J3.SetActive(false);
            J4.SetActive(false);
            J5.SetActive(false);
            J6.SetActive(false);
            J7.SetActive(false);
            J8.SetActive(false);
            J9.SetActive(false);
            J10.SetActive(false);
            J11.SetActive(false);
            J12.SetActive(false);
            J13.SetActive(false);
            J14.SetActive(false);
            J15.SetActive(false);
            J16.SetActive(false);
            J17.SetActive(true);
            J18.SetActive(false);
            J19.SetActive(false);
            J20.SetActive(false);
            J21.SetActive(false);
            J22.SetActive(false);
            J23.SetActive(false);
            J24.SetActive(false);
            J25.SetActive(false);
            J26.SetActive(false);
            J27.SetActive(false);
            J28.SetActive(false);
            J29.SetActive(false);
            J30.SetActive(false);
            J31.SetActive(false);
            J32.SetActive(false);
            J33.SetActive(false);
            J34.SetActive(false);
            J35.SetActive(false);
        }

        if (Controlador.Juegoselec == 18)
        {
            J1.SetActive(false);
            J2.SetActive(false);
            J3.SetActive(false);
            J4.SetActive(false);
            J5.SetActive(false);
            J6.SetActive(false);
            J7.SetActive(false);
            J8.SetActive(false);
            J9.SetActive(false);
            J10.SetActive(false);
            J11.SetActive(false);
            J12.SetActive(false);
            J13.SetActive(false);
            J14.SetActive(false);
            J15.SetActive(false);
            J16.SetActive(false);
            J17.SetActive(false);
            J18.SetActive(true);
            J19.SetActive(false);
            J20.SetActive(false);
            J21.SetActive(false);
            J22.SetActive(false);
            J23.SetActive(false);
            J24.SetActive(false);
            J25.SetActive(false);
            J26.SetActive(false);
            J27.SetActive(false);
            J28.SetActive(false);
            J29.SetActive(false);
            J30.SetActive(false);
            J31.SetActive(false);
            J32.SetActive(false);
            J33.SetActive(false);
            J34.SetActive(false);
            J35.SetActive(false);
        }

        if (Controlador.Juegoselec == 19)
        {
            J1.SetActive(false);
            J2.SetActive(false);
            J3.SetActive(false);
            J4.SetActive(false);
            J5.SetActive(false);
            J6.SetActive(false);
            J7.SetActive(false);
            J8.SetActive(false);
            J9.SetActive(false);
            J10.SetActive(false);
            J11.SetActive(false);
            J12.SetActive(false);
            J13.SetActive(false);
            J14.SetActive(false);
            J15.SetActive(false);
            J16.SetActive(false);
            J17.SetActive(false);
            J18.SetActive(false);
            J19.SetActive(true);
            J20.SetActive(false);
            J21.SetActive(false);
            J22.SetActive(false);
            J23.SetActive(false);
            J24.SetActive(false);
            J25.SetActive(false);
            J26.SetActive(false);
            J27.SetActive(false);
            J28.SetActive(false);
            J29.SetActive(false);
            J30.SetActive(false);
            J31.SetActive(false);
            J32.SetActive(false);
            J33.SetActive(false);
            J34.SetActive(false);
            J35.SetActive(false);
        }

        if (Controlador.Juegoselec == 20)
        {
            J1.SetActive(false);
            J2.SetActive(false);
            J3.SetActive(false);
            J4.SetActive(false);
            J5.SetActive(false);
            J6.SetActive(false);
            J7.SetActive(false);
            J8.SetActive(false);
            J9.SetActive(false);
            J10.SetActive(false);
            J11.SetActive(false);
            J12.SetActive(false);
            J13.SetActive(false);
            J14.SetActive(false);
            J15.SetActive(false);
            J16.SetActive(false);
            J17.SetActive(false);
            J18.SetActive(false);
            J19.SetActive(false);
            J20.SetActive(true);
            J21.SetActive(false);
            J22.SetActive(false);
            J23.SetActive(false);
            J24.SetActive(false);
            J25.SetActive(false);
            J26.SetActive(false);
            J27.SetActive(false);
            J28.SetActive(false);
            J29.SetActive(false);
            J30.SetActive(false);
            J31.SetActive(false);
            J32.SetActive(false);
            J33.SetActive(false);
            J34.SetActive(false);
            J35.SetActive(false);
        }

        if (Controlador.Juegoselec == 21)
        {
            J1.SetActive(false);
            J2.SetActive(false);
            J3.SetActive(false);
            J4.SetActive(false);
            J5.SetActive(false);
            J6.SetActive(false);
            J7.SetActive(false);
            J8.SetActive(false);
            J9.SetActive(false);
            J10.SetActive(false);
            J11.SetActive(false);
            J12.SetActive(false);
            J13.SetActive(false);
            J14.SetActive(false);
            J15.SetActive(false);
            J16.SetActive(false);
            J17.SetActive(false);
            J18.SetActive(false);
            J19.SetActive(false);
            J20.SetActive(false);
            J21.SetActive(true);
            J22.SetActive(false);
            J23.SetActive(false);
            J24.SetActive(false);
            J25.SetActive(false);
            J26.SetActive(false);
            J27.SetActive(false);
            J28.SetActive(false);
            J29.SetActive(false);
            J30.SetActive(false);
            J31.SetActive(false);
            J32.SetActive(false);
            J33.SetActive(false);
            J34.SetActive(false);
            J35.SetActive(false);
        }

        if (Controlador.Juegoselec == 22)
        {
            J1.SetActive(false);
            J2.SetActive(false);
            J3.SetActive(false);
            J4.SetActive(false);
            J5.SetActive(false);
            J6.SetActive(false);
            J7.SetActive(false);
            J8.SetActive(false);
            J9.SetActive(false);
            J10.SetActive(false);
            J11.SetActive(false);
            J12.SetActive(false);
            J13.SetActive(false);
            J14.SetActive(false);
            J15.SetActive(false);
            J16.SetActive(false);
            J17.SetActive(false);
            J18.SetActive(false);
            J19.SetActive(false);
            J20.SetActive(false);
            J21.SetActive(false);
            J22.SetActive(true);
            J23.SetActive(false);
            J24.SetActive(false);
            J25.SetActive(false);
            J26.SetActive(false);
            J27.SetActive(false);
            J28.SetActive(false);
            J29.SetActive(false);
            J30.SetActive(false);
            J31.SetActive(false);
            J32.SetActive(false);
            J33.SetActive(false);
            J34.SetActive(false);
            J35.SetActive(false);
        }

        if (Controlador.Juegoselec == 23)
        {
            J1.SetActive(false);
            J2.SetActive(false);
            J3.SetActive(false);
            J4.SetActive(false);
            J5.SetActive(false);
            J6.SetActive(false);
            J7.SetActive(false);
            J8.SetActive(false);
            J9.SetActive(false);
            J10.SetActive(false);
            J11.SetActive(false);
            J12.SetActive(false);
            J13.SetActive(false);
            J14.SetActive(false);
            J15.SetActive(false);
            J16.SetActive(false);
            J17.SetActive(false);
            J18.SetActive(false);
            J19.SetActive(false);
            J20.SetActive(false);
            J21.SetActive(false);
            J22.SetActive(false);
            J23.SetActive(true);
            J24.SetActive(false);
            J25.SetActive(false);
            J26.SetActive(false);
            J27.SetActive(false);
            J28.SetActive(false);
            J29.SetActive(false);
            J30.SetActive(false);
            J31.SetActive(false);
            J32.SetActive(false);
            J33.SetActive(false);
            J34.SetActive(false);
            J35.SetActive(false);
        }

        if (Controlador.Juegoselec == 24)
        {
            J1.SetActive(false);
            J2.SetActive(false);
            J3.SetActive(false);
            J4.SetActive(false);
            J5.SetActive(false);
            J6.SetActive(false);
            J7.SetActive(false);
            J8.SetActive(false);
            J9.SetActive(false);
            J10.SetActive(false);
            J11.SetActive(false);
            J12.SetActive(false);
            J13.SetActive(false);
            J14.SetActive(false);
            J15.SetActive(false);
            J16.SetActive(false);
            J17.SetActive(false);
            J18.SetActive(false);
            J19.SetActive(false);
            J20.SetActive(false);
            J21.SetActive(false);
            J22.SetActive(false);
            J23.SetActive(false);
            J24.SetActive(true);
            J25.SetActive(false);
            J26.SetActive(false);
            J27.SetActive(false);
            J28.SetActive(false);
            J29.SetActive(false);
            J30.SetActive(false);
            J31.SetActive(false);
            J32.SetActive(false);
            J33.SetActive(false);
            J34.SetActive(false);
            J35.SetActive(false);
        }

        if (Controlador.Juegoselec == 25)
        {
            J1.SetActive(false);
            J2.SetActive(false);
            J3.SetActive(false);
            J4.SetActive(false);
            J5.SetActive(false);
            J6.SetActive(false);
            J7.SetActive(false);
            J8.SetActive(false);
            J9.SetActive(false);
            J10.SetActive(false);
            J11.SetActive(false);
            J12.SetActive(false);
            J13.SetActive(false);
            J14.SetActive(false);
            J15.SetActive(false);
            J16.SetActive(false);
            J17.SetActive(false);
            J18.SetActive(false);
            J19.SetActive(false);
            J20.SetActive(false);
            J21.SetActive(false);
            J22.SetActive(false);
            J23.SetActive(false);
            J24.SetActive(false);
            J25.SetActive(true);
            J26.SetActive(false);
            J27.SetActive(false);
            J28.SetActive(false);
            J29.SetActive(false);
            J30.SetActive(false);
            J31.SetActive(false);
            J32.SetActive(false);
            J33.SetActive(false);
            J34.SetActive(false);
            J35.SetActive(false);
        }

        if (Controlador.Juegoselec == 26)
        {
            J1.SetActive(false);
            J2.SetActive(false);
            J3.SetActive(false);
            J4.SetActive(false);
            J5.SetActive(false);
            J6.SetActive(false);
            J7.SetActive(false);
            J8.SetActive(false);
            J9.SetActive(false);
            J10.SetActive(false);
            J11.SetActive(false);
            J12.SetActive(false);
            J13.SetActive(false);
            J14.SetActive(false);
            J15.SetActive(false);
            J16.SetActive(false);
            J17.SetActive(false);
            J18.SetActive(false);
            J19.SetActive(false);
            J20.SetActive(false);
            J21.SetActive(false);
            J22.SetActive(false);
            J23.SetActive(false);
            J24.SetActive(false);
            J25.SetActive(false);
            J26.SetActive(true);
            J27.SetActive(false);
            J28.SetActive(false);
            J29.SetActive(false);
            J30.SetActive(false);
            J31.SetActive(false);
            J32.SetActive(false);
            J33.SetActive(false);
            J34.SetActive(false);
            J35.SetActive(false);
        }

        if (Controlador.Juegoselec == 27)
        {
            J1.SetActive(false);
            J2.SetActive(false);
            J3.SetActive(false);
            J4.SetActive(false);
            J5.SetActive(false);
            J6.SetActive(false);
            J7.SetActive(false);
            J8.SetActive(false);
            J9.SetActive(false);
            J10.SetActive(false);
            J11.SetActive(false);
            J12.SetActive(false);
            J13.SetActive(false);
            J14.SetActive(false);
            J15.SetActive(false);
            J16.SetActive(false);
            J17.SetActive(false);
            J18.SetActive(false);
            J19.SetActive(false);
            J20.SetActive(false);
            J21.SetActive(false);
            J22.SetActive(false);
            J23.SetActive(false);
            J24.SetActive(false);
            J25.SetActive(false);
            J26.SetActive(false);
            J27.SetActive(true);
            J28.SetActive(false);
            J29.SetActive(false);
            J30.SetActive(false);
            J31.SetActive(false);
            J32.SetActive(false);
            J33.SetActive(false);
            J34.SetActive(false);
            J35.SetActive(false);
        }

        if (Controlador.Juegoselec == 28)
        {
            J1.SetActive(false);
            J2.SetActive(false);
            J3.SetActive(false);
            J4.SetActive(false);
            J5.SetActive(false);
            J6.SetActive(false);
            J7.SetActive(false);
            J8.SetActive(false);
            J9.SetActive(false);
            J10.SetActive(false);
            J11.SetActive(false);
            J12.SetActive(false);
            J13.SetActive(false);
            J14.SetActive(false);
            J15.SetActive(false);
            J16.SetActive(false);
            J17.SetActive(false);
            J18.SetActive(false);
            J19.SetActive(false);
            J20.SetActive(false);
            J21.SetActive(false);
            J22.SetActive(false);
            J23.SetActive(false);
            J24.SetActive(false);
            J25.SetActive(false);
            J26.SetActive(false);
            J27.SetActive(false);
            J28.SetActive(true);
            J29.SetActive(false);
            J30.SetActive(false);
            J31.SetActive(false);
            J32.SetActive(false);
            J33.SetActive(false);
            J34.SetActive(false);
            J35.SetActive(false);
        }

        if (Controlador.Juegoselec == 29)
        {
            J1.SetActive(false);
            J2.SetActive(false);
            J3.SetActive(false);
            J4.SetActive(false);
            J5.SetActive(false);
            J6.SetActive(false);
            J7.SetActive(false);
            J8.SetActive(false);
            J9.SetActive(false);
            J10.SetActive(false);
            J11.SetActive(false);
            J12.SetActive(false);
            J13.SetActive(false);
            J14.SetActive(false);
            J15.SetActive(false);
            J16.SetActive(false);
            J17.SetActive(false);
            J18.SetActive(false);
            J19.SetActive(false);
            J20.SetActive(false);
            J21.SetActive(false);
            J22.SetActive(false);
            J23.SetActive(false);
            J24.SetActive(false);
            J25.SetActive(false);
            J26.SetActive(false);
            J27.SetActive(false);
            J28.SetActive(false);
            J29.SetActive(true);
            J30.SetActive(false);
            J31.SetActive(false);
            J32.SetActive(false);
            J33.SetActive(false);
            J34.SetActive(false);
            J35.SetActive(false);
        }

        if (Controlador.Juegoselec == 30)
        {
            J1.SetActive(false);
            J2.SetActive(false);
            J3.SetActive(false);
            J4.SetActive(false);
            J5.SetActive(false);
            J6.SetActive(false);
            J7.SetActive(false);
            J8.SetActive(false);
            J9.SetActive(false);
            J10.SetActive(false);
            J11.SetActive(false);
            J12.SetActive(false);
            J13.SetActive(false);
            J14.SetActive(false);
            J15.SetActive(false);
            J16.SetActive(false);
            J17.SetActive(false);
            J18.SetActive(false);
            J19.SetActive(false);
            J20.SetActive(false);
            J21.SetActive(false);
            J22.SetActive(false);
            J23.SetActive(false);
            J24.SetActive(false);
            J25.SetActive(false);
            J26.SetActive(false);
            J27.SetActive(false);
            J28.SetActive(false);
            J29.SetActive(false);
            J30.SetActive(true);
            J31.SetActive(false);
            J32.SetActive(false);
            J33.SetActive(false);
            J34.SetActive(false);
            J35.SetActive(false);
        }


        if (Controlador.Juegoselec == 31)
        {
            J1.SetActive(false);
            J2.SetActive(false);
            J3.SetActive(false);
            J4.SetActive(false);
            J5.SetActive(false);
            J6.SetActive(false);
            J7.SetActive(false);
            J8.SetActive(false);
            J9.SetActive(false);
            J10.SetActive(false);
            J11.SetActive(false);
            J12.SetActive(false);
            J13.SetActive(false);
            J14.SetActive(false);
            J15.SetActive(false);
            J16.SetActive(false);
            J17.SetActive(false);
            J18.SetActive(false);
            J19.SetActive(false);
            J20.SetActive(false);
            J21.SetActive(false);
            J22.SetActive(false);
            J23.SetActive(false);
            J24.SetActive(false);
            J25.SetActive(false);
            J26.SetActive(false);
            J27.SetActive(false);
            J28.SetActive(false);
            J29.SetActive(false);
            J30.SetActive(false);
            J31.SetActive(true);
            J32.SetActive(false);
            J33.SetActive(false);
            J34.SetActive(false);
            J35.SetActive(false);
        }

        if (Controlador.Juegoselec == 32)
        {
            J1.SetActive(false);
            J2.SetActive(false);
            J3.SetActive(false);
            J4.SetActive(false);
            J5.SetActive(false);
            J6.SetActive(false);
            J7.SetActive(false);
            J8.SetActive(false);
            J9.SetActive(false);
            J10.SetActive(false);
            J11.SetActive(false);
            J12.SetActive(false);
            J13.SetActive(false);
            J14.SetActive(false);
            J15.SetActive(false);
            J16.SetActive(false);
            J17.SetActive(false);
            J18.SetActive(false);
            J19.SetActive(false);
            J20.SetActive(false);
            J21.SetActive(false);
            J22.SetActive(false);
            J23.SetActive(false);
            J24.SetActive(false);
            J25.SetActive(false);
            J26.SetActive(false);
            J27.SetActive(false);
            J28.SetActive(false);
            J29.SetActive(false);
            J30.SetActive(false);
            J31.SetActive(false);
            J32.SetActive(true);
            J33.SetActive(false);
            J34.SetActive(false);
            J35.SetActive(false);
        }

        if (Controlador.Juegoselec == 33)
        {
            J1.SetActive(false);
            J2.SetActive(false);
            J3.SetActive(false);
            J4.SetActive(false);
            J5.SetActive(false);
            J6.SetActive(false);
            J7.SetActive(false);
            J8.SetActive(false);
            J9.SetActive(false);
            J10.SetActive(false);
            J11.SetActive(false);
            J12.SetActive(false);
            J13.SetActive(false);
            J14.SetActive(false);
            J15.SetActive(false);
            J16.SetActive(false);
            J17.SetActive(false);
            J18.SetActive(false);
            J19.SetActive(false);
            J20.SetActive(false);
            J21.SetActive(false);
            J22.SetActive(false);
            J23.SetActive(false);
            J24.SetActive(false);
            J25.SetActive(false);
            J26.SetActive(false);
            J27.SetActive(false);
            J28.SetActive(false);
            J29.SetActive(false);
            J30.SetActive(false);
            J31.SetActive(false);
            J32.SetActive(false);
            J33.SetActive(true);
            J34.SetActive(false);
            J35.SetActive(false);
        }

        if (Controlador.Juegoselec == 34)
        {
            J1.SetActive(false);
            J2.SetActive(false);
            J3.SetActive(false);
            J4.SetActive(false);
            J5.SetActive(false);
            J6.SetActive(false);
            J7.SetActive(false);
            J8.SetActive(false);
            J9.SetActive(false);
            J10.SetActive(false);
            J11.SetActive(false);
            J12.SetActive(false);
            J13.SetActive(false);
            J14.SetActive(false);
            J15.SetActive(false);
            J16.SetActive(false);
            J17.SetActive(false);
            J18.SetActive(false);
            J19.SetActive(false);
            J20.SetActive(false);
            J21.SetActive(false);
            J22.SetActive(false);
            J23.SetActive(false);
            J24.SetActive(false);
            J25.SetActive(false);
            J26.SetActive(false);
            J27.SetActive(false);
            J28.SetActive(false);
            J29.SetActive(false);
            J30.SetActive(false);
            J31.SetActive(false);
            J32.SetActive(false);
            J33.SetActive(false);
            J34.SetActive(true);
            J35.SetActive(false);
        }

        if (Controlador.Juegoselec == 35)
        {
            J1.SetActive(false);
            J2.SetActive(false);
            J3.SetActive(false);
            J4.SetActive(false);
            J5.SetActive(false);
            J6.SetActive(false);
            J7.SetActive(false);
            J8.SetActive(false);
            J9.SetActive(false);
            J10.SetActive(false);
            J11.SetActive(false);
            J12.SetActive(false);
            J13.SetActive(false);
            J14.SetActive(false);
            J15.SetActive(false);
            J16.SetActive(false);
            J17.SetActive(false);
            J18.SetActive(false);
            J19.SetActive(false);
            J20.SetActive(false);
            J21.SetActive(false);
            J22.SetActive(false);
            J23.SetActive(false);
            J24.SetActive(false);
            J25.SetActive(false);
            J26.SetActive(false);
            J27.SetActive(false);
            J28.SetActive(false);
            J29.SetActive(false);
            J30.SetActive(false);
            J31.SetActive(false);
            J32.SetActive(false);
            J33.SetActive(false);
            J34.SetActive(false);
            J35.SetActive(true);
        }
















    }
}
